version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: cythonize-package:latest
    container_name: cythonize-package-app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
